export const state = {
  snackbar: {
    status: false,
    value: 'Felmeddelandetext',
    color: 'green lighten-2',
    timeout: 5000,
    hasLink: false,
    linkUrl: '',
  },
  user: {
    id: 1,
    school: '',
    pagesRead: 0,
    booksRead: 0,
    reviewsWritten: 0,
    points: 0,
    role: '', // student, teacher, admin
    roleId: 1,
    roleType: '',
    avatarId: 1,
    avatarIcon: 'karate',
    avatarDisplayName: 'ninja',
    avatarColorDisplayName: 'Blå',
    avatarColor: 'blue',
    class: {
      pagesRead: 0,
      booksRead: 0,
      reviewsWritten: 0,
      id: 0,
    },
  },
  token: true,
  navbarIcon: false,
  skolon: false,
  adminLoginModal: false,
  isLoading: false,
  userAgent: {
    isMobile: null,
  },
  books: [],
  authors: Array[Object],
  genres: Array[Object],
  classes: [],
  schoolUnit: Array[Object],
  highestRatedBooks: [],
  recentlyReviewedBooks: [],
};